<?php

namespace App\Libraries;

use App\Models\AppSettingModel;
use App\Models\UserModel;
use Config\Database;
use Config\Services;
use mysqli;
use RuntimeException;

class InstallerService
{
    public const LOCK_FILE = WRITEPATH . 'installed.lock';

    /**
     * @param array{hostname: string, database: string, username: string, password: string, port?: int} $config
     */
    public function testConnection(array $config): bool
    {
        $mysqli = @new mysqli(
            $config['hostname'],
            $config['username'],
            $config['password'],
            '',
            (int) ($config['port'] ?? 3306)
        );

        if ($mysqli->connect_errno) {
            return false;
        }

        $dbName = $config['database'];
        $escaped = $mysqli->real_escape_string($dbName);
        $mysqli->query("CREATE DATABASE IF NOT EXISTS `{$escaped}` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci");
        $mysqli->select_db($dbName);
        $ok = $mysqli->errno === 0;
        $mysqli->close();

        return $ok;
    }

    /**
     * @param array{hostname: string, database: string, username: string, password: string, port?: int} $db
     */
    public function writeEnv(array $db, string $baseUrl, string $encryptionKey): void
    {
        $envPath = ROOTPATH . '.env';
        $lines   = [
            '# Generated by S3 installer',
            'CI_ENVIRONMENT = production',
            '',
            'app.baseURL = ' . rtrim($baseUrl, '/') . '/',
            'encryption.key = ' . $encryptionKey,
            '',
            'database.default.hostname = ' . $db['hostname'],
            'database.default.database = ' . $db['database'],
            'database.default.username = ' . $db['username'],
            'database.default.password = ' . $this->escapeEnvValue($db['password']),
            'database.default.DBDriver = MySQLi',
            'database.default.DBPrefix =',
            'database.default.port = ' . (int) ($db['port'] ?? 3306),
            '',
        ];

        if (! is_file($envPath)) {
            $example = ROOTPATH . 'env';
            if (is_readable($example)) {
                $template = file_get_contents($example);
                if ($template !== false) {
                    $lines = explode("\n", $this->mergeEnvTemplate($template, $db, $baseUrl, $encryptionKey));
                }
            }
        }

        $content = implode("\n", $lines) . "\n";
        if (file_put_contents($envPath, $content) === false) {
            throw new RuntimeException('Gagal menulis file .env. Periksa izin folder.');
        }
    }

    public function reloadEnvironment(): void
    {
        if (is_file(ROOTPATH . '.env')) {
            (new \CodeIgniter\Config\DotEnv(ROOTPATH))->load();
        }
        putenv('CI_ENVIRONMENT=production');
        $_ENV['CI_ENVIRONMENT']    = 'production';
        $_SERVER['CI_ENVIRONMENT'] = 'production';
    }

    public function runMigrations(): void
    {
        $runner = Services::migrations();
        if (! $runner->latest()) {
            throw new RuntimeException('Migrasi database gagal.');
        }
    }

    /**
     * @param array{nama: string, email: string, password: string} $admin
     */
    public function createAdmin(array $admin): int
    {
        $model = new UserModel();
        $existing = $model->where('email', $admin['email'])->first();
        if ($existing) {
            return (int) $existing['id'];
        }

        return (int) $model->insert([
            'nip'                  => null,
            'nama'                 => $admin['nama'],
            'email'                => $admin['email'],
            'password'             => $admin['password'],
            'role'                 => 'kurikulum',
            'is_admin'             => 1,
            'must_change_password' => 0,
            'is_active'            => 1,
        ], true);
    }

    /**
     * @param array{nama_sekolah: string, logo_path?: ?string} $school
     */
    public function saveSchoolProfile(array $school): void
    {
        $app = new AppSettingModel();
        $row = $app->orderBy('id', 'ASC')->first();
        $payload = [
            'nama_sekolah' => $school['nama_sekolah'],
            'logo_path'    => $school['logo_path'] ?? null,
        ];
        if ($row) {
            $app->update($row['id'], $payload);
        } else {
            $app->insert($payload);
        }

        SettingsService::set('school.name', $payload['nama_sekolah']);
        SettingsService::set('school.logo_path', $payload['logo_path']);
        BrandingService::clearCache();
    }

    public function seedEmptyTemplate(): void
    {
        $db = Database::connect();

        if ($db->table('hari')->countAllResults() === 0) {
            $days = [
                ['nama' => 'Senin', 'kode' => 'SEN', 'urutan' => 1],
                ['nama' => 'Selasa', 'kode' => 'SEL', 'urutan' => 2],
                ['nama' => 'Rabu', 'kode' => 'RAB', 'urutan' => 3],
                ['nama' => 'Kamis', 'kode' => 'KAM', 'urutan' => 4],
                ['nama' => 'Jumat', 'kode' => 'JUM', 'urutan' => 5],
                ['nama' => 'Sabtu', 'kode' => 'SAB', 'urutan' => 6],
            ];
            $db->table('hari')->insertBatch($days);
        }

        if ($db->table('timeslot')->countAllResults() > 0) {
            return;
        }

        $hariRows = $db->table('hari')->orderBy('urutan', 'ASC')->get()->getResultArray();
        $now      = date('Y-m-d H:i:s');
        $slots    = [];

        foreach ($hariRows as $hari) {
            $hid = (int) $hari['id'];
            $isMonday = $hari['kode'] === 'SEN';
            if ($isMonday) {
                $pattern = [
                    [0, '06:45:00', '07:25:00', 'kegiatan_khusus', 'Upacara'],
                    [1, '07:25:00', '08:15:00', 'jp', ''],
                    [2, '08:15:00', '08:50:00', 'jp', ''],
                    [3, '08:50:00', '09:25:00', 'jp', ''],
                    [4, '09:25:00', '10:10:00', 'jp', ''],
                    [0, '10:10:00', '10:30:00', 'istirahat', 'Istirahat 1'],
                    [5, '10:30:00', '11:10:00', 'jp', ''],
                    [6, '11:10:00', '11:50:00', 'jp', ''],
                    [7, '11:50:00', '12:30:00', 'jp', ''],
                    [0, '12:30:00', '13:00:00', 'istirahat', 'Istirahat 2'],
                    [8, '13:00:00', '13:40:00', 'jp', ''],
                    [9, '13:40:00', '14:20:00', 'jp', ''],
                    [10, '14:20:00', '15:00:00', 'jp', ''],
                ];
            } else {
                $pattern = [
                    [1, '07:00:00', '07:40:00', 'jp', ''],
                    [2, '07:40:00', '08:20:00', 'jp', ''],
                    [3, '08:20:00', '09:00:00', 'jp', ''],
                    [4, '09:00:00', '09:40:00', 'jp', ''],
                    [0, '09:40:00', '10:00:00', 'istirahat', 'Istirahat'],
                    [5, '10:00:00', '10:40:00', 'jp', ''],
                    [6, '10:40:00', '11:20:00', 'jp', ''],
                    [7, '11:20:00', '12:00:00', 'jp', ''],
                    [0, '12:00:00', '12:30:00', 'istirahat', 'Istirahat'],
                    [8, '12:30:00', '13:10:00', 'jp', ''],
                    [9, '13:10:00', '13:50:00', 'jp', ''],
                ];
            }

            foreach ($pattern as $p) {
                $slots[] = [
                    'hari_id'       => $hid,
                    'jam_ke'        => $p[0],
                    'waktu_mulai'   => $p[1],
                    'waktu_selesai' => $p[2],
                    'tipe'          => $p[3],
                    'keterangan'    => $p[4] !== '' ? $p[4] : null,
                    'created_at'    => $now,
                    'updated_at'    => $now,
                ];
            }
        }

        $db->table('timeslot')->insertBatch($slots);
    }

    public function writeLock(): void
    {
        $payload = json_encode([
            'installed_at' => date('c'),
            'version'      => '1.0.0',
        ], JSON_UNESCAPED_UNICODE);

        if (file_put_contents(self::LOCK_FILE, $payload . "\n") === false) {
            throw new RuntimeException('Gagal menulis installed.lock di folder writable.');
        }
    }

    public function isInstalled(): bool
    {
        return is_file(self::LOCK_FILE);
    }

    public static function generateEncryptionKey(): string
    {
        return bin2hex(random_bytes(32));
    }

    private function escapeEnvValue(string $value): string
    {
        if ($value === '' || preg_match('/\s|#|=/', $value)) {
            return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
        }

        return $value;
    }

    /**
     * @param array{hostname: string, database: string, username: string, password: string, port?: int} $db
     */
    private function mergeEnvTemplate(string $template, array $db, string $baseUrl, string $encryptionKey): string
    {
        $replacements = [
            'app.baseURL'                 => rtrim($baseUrl, '/') . '/',
            'encryption.key'              => $encryptionKey,
            'database.default.hostname'   => $db['hostname'],
            'database.default.database'   => $db['database'],
            'database.default.username'   => $db['username'],
            'database.default.password'   => $db['password'],
            'database.default.port'       => (string) (int) ($db['port'] ?? 3306),
            'CI_ENVIRONMENT'              => 'production',
        ];

        $lines = preg_split('/\r\n|\r|\n/', $template) ?: [];
        $out   = [];
        $seen  = [];

        foreach ($lines as $line) {
            $trim = trim($line);
            if ($trim === '' || str_starts_with($trim, '#')) {
                $out[] = $line;
                continue;
            }
            $parts = explode('=', $line, 2);
            $key   = trim($parts[0]);
            if (array_key_exists($key, $replacements)) {
                $out[] = $key . ' = ' . $this->escapeEnvValue((string) $replacements[$key]);
                $seen[$key] = true;
            } else {
                $out[] = $line;
            }
        }

        foreach ($replacements as $key => $val) {
            if (! isset($seen[$key])) {
                $out[] = $key . ' = ' . $this->escapeEnvValue((string) $val);
            }
        }

        return implode("\n", $out);
    }
}
